[package]
name = "bitcoin-address-tutorial"
version = "0.1.0"
authors = ["samparsky <8148384+samparsky@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
